[[mgr.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on = "<Enter>"
run = 'noop'
desc = "Do nothing!"

[[mgr.prepend_keymap]]
on = "<C-d>"
run = 'shell -- ripdrag -x -A -W 200 -H 100 "$@" &'
desc = "Drag and drop using ripdrag"
